#ifndef GLOBAL_VARIABLES_H
#define GLOBAL_VARIABLES_H

enum STATE
{
    STATE_IDLE,
    STATE_WALKING,
    STATE_DECELERATING,
    STATE_JUMPING,
    STATE_FALLING,
    STATE_DUCKING,
    STATE_SWIMMING
};

enum DIRECTION
{
    LEFT,
    RIGHT
};

enum MARIO_FORM
{
    SMALL,
    BIG,
    FIRE,
    SUPER
};

enum TileState
{
    STATE_NORMAL,
    STATE_ACTIVATED,
    STATE_INTERACTED,
    STATE_BROKEN
};

#define MARIO_WIDTH 32.0f
#define MARIO_HEIGHT 32.0f
#define FRAME_PADDING 2
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240
#define SCALE 2.0f
#define GRID_WIDTH 211
#define GRID_WIDTH_2 163
#define GRID_HEIGHT 15
#define TILE_SIZE 16.0f

#endif // GLOBAL_VARIABLES_H