#ifndef GLOBAL_VARIABLES_H
#define GLOBAL_VARIABLES_H

enum STATE
{
    STATE_IDLE,
    STATE_WALKING,
    STATE_JUMPING,
    STATE_FALLING,
    STATE_DUCKING,
    STATE_SWIMMING
};

#endif // GLOBAL_VARIABLES_H