#ifndef GLOBAL_VARIABLES_H
#define GLOBAL_VARIABLES_H

enum STATE
{
    STATE_IDLE,
    STATE_WALKING,
    STATE_DECELERATING,
    STATE_JUMPING,
    STATE_FALLING,
    STATE_DUCKING,
    STATE_DEAD,
    STATE_SLIDING,
    STATE_THROWING,
};

enum CHARACTER
{
    NONE,
    MARIO,
    LUIGI
};

enum DIRECTION
{
    LEFT,
    RIGHT
};

enum CHARACTER_FORM
{
    SMALL,
    BIG,
    FIRE,
    SUPER
};

enum TileState
{
    STATE_NORMAL,
    STATE_ACTIVATED,
    STATE_INTERACTED,
    STATE_BROKEN
};

#define CHARACTER_WIDTH 32.0f
#define CHARACTER_HEIGHT 32.0f
#define FRAME_PADDING 2
#define SCREEN_WIDTH 400
#define SCREEN_HEIGHT 240
#define SCALE 2.0f
#define GRID_WIDTH 211
#define GRID_WIDTH_2 163
#define GRID_HEIGHT 15
#define TILE_SIZE 16.0f
#define FLAG_SPEED 200.0f
#define GRID_HEIGHT 15
#define HEIGHT_BOUNDARY GRID_HEIGHT * TILE_SIZE * SCALE
#define FIREBAR_ANGLE_VELOCITY 10 / ( 2 * M_PI ) 
#define FIREBALL_SIZE 8 * SCALE

#define START_POS_WORLD_1_1 Vector2({6 * TILE_SIZE * SCALE, 13 * TILE_SIZE * SCALE})
#define THROWING_FRAME_THRESHOLD 30 // 6fps

#endif // GLOBAL_VARIABLES_H